name: Trigger deploy Nogin API

on:
  workflow_dispatch:
    inputs:
      from-branch:
        description: 'base branch to deploy dev'
        required: true
        default: 'test-deploy' 
      target-branch:
        description: 'Target branch to deploy deploy-dev'
        required: true
        default: 'master' 

jobs:
  rebase-and-push:
    name: Rebase and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Checkout the `${{ github.event.inputs.from-branch }}` branch and pull the latest changes
      - name: Checkout and Pull Dev Branch
        run: |
          git fetch 
          git checkout ${{ github.event.inputs.from-branch }}
          git pull origin ${{ github.event.inputs.from-branch }}

      # Checkout the target branch deploy-dev, pull, and rebase on `${{ github.event.inputs.from-branch }}`
      - name: Checkout and Rebase Target Branch
        run: |
          set -x  # Enable command tracing
          git config --global user.email "royjimval@gmail.com"
          git config --global user.name "RoyJimenezValdez"
          git status
          git fetch 
          git checkout ${{ github.event.inputs.target-branch }}
          git pull origin ${{ github.event.inputs.target-branch }}
          git rebase  ${{ github.event.inputs.from-branch }} 
          

      # Log the changes for confirmation
      - name: Show Git Log
        run: git log --oneline -n 10

      # Push the rebased branch back to the remote
      - name: Push Rebases to Target Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force-with-lease origin ${{ github.event.inputs.target-branch }}

      # Notify the action is done
      - name: Complete
        run: echo "Rebase and deployment process started successfully!"
