name: Trigger deploy Nogin API V2

on:
  workflow_dispatch:
    inputs:
      from-branch:
        description: 'Base branch to deploy (ex. dev)'
        required: true
        type: choice
        options:
          - dev-deploy
          - next
          - main

jobs:
  rebase-and-push:
    name: Rebase and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Determine the target branch dynamically
      - name: Set Target Branch
        id: set-target-branch
        run: |
          case "${{ github.event.inputs.from-branch }}" in
            dev-deploy)
              echo "target-branch=master" >> $GITHUB_ENV
              ;;
            next)
              echo "target-branch=deploy-next" >> $GITHUB_ENV
              ;;
            main)
              echo "target-branch=deploy-main" >> $GITHUB_ENV
              ;;
            *)
              echo "Error: Unsupported from-branch value" >&2
              exit 1
              ;;
          esac

      # Perform the rebase process
      - name: Rebase and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.email "rjimenez@nogin.com"
            git config --global user.name "RoyJimenezValdez"
            git fetch origin
            git checkout ${{ env.target-branch }}
            git pull origin ${{ env.target-branch }}
            git fetch origin ${{ github.event.inputs.from-branch }}:${{ github.event.inputs.from-branch }}
            git rebase ${{ github.event.inputs.from-branch }} || (
                echo "Rebase failed. Resolving conflicts automatically." &&
                git rebase --abort &&
                git merge --strategy=recursive -X theirs ${{ github.event.inputs.from-branch }} --allow-unrelated-histories
            )

            git push --force origin ${{ env.target-branch }}

      # Notify the action is complete
      - name: Complete
        run: echo "Rebase and deployment process completed successfully!"
